# Generated by Django 4.2.16 on 2024-11-09 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_paciente_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocategoria',
            name='categoria_examen',
        ),
        migrations.DeleteModel(
            name='CategoriaExamen',
        ),
        migrations.DeleteModel(
            name='TipoCategoria',
        ),
    ]
