# Generated by Django 5.1.3 on 2024-11-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_medicamento_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marcamedicamento',
            options={'verbose_name': 'Marca de Medicamento', 'verbose_name_plural': 'Marcas de Medicamentos'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True, verbose_name='Longitud'),
        ),
    ]
