# Generated by Django 5.1.3 on 2024-11-22 02:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_marcamedicamento_options_alter_doctor_latitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(default=datetime.date.today, verbose_name='Fecha de Emisión')),
                ('motivo', models.TextField(verbose_name='Motivo/Diagnóstico')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Adicional')),
                ('duracion_reposo', models.IntegerField(blank=True, null=True, verbose_name='Duración de Reposo (días)')),
                ('firma', models.ImageField(blank=True, null=True, upload_to='firmas_certificados/', verbose_name='Firma del Certificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados', to='core.doctor', verbose_name='Doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='core.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
