# Generated by Django 5.1.3 on 2024-11-22 11:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_certificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField(default=datetime.date.today, verbose_name='Fecha de la Consulta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de la Consulta')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(blank=True, null=True, verbose_name='Tratamiento')),
                ('procedimientos', models.TextField(blank=True, null=True, verbose_name='Procedimientos Realizados')),
                ('receta', models.TextField(blank=True, null=True, verbose_name='Receta Médica')),
                ('adjuntos', models.FileField(blank=True, null=True, upload_to='fichas_clinicas/', verbose_name='Archivos Adjuntos')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_clinicas', to='core.doctor', verbose_name='Doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_clinicas', to='core.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Ficha Clínica',
                'verbose_name_plural': 'Fichas Clínicas',
                'ordering': ['-fecha_consulta'],
                'indexes': [models.Index(fields=['fecha_consulta', 'paciente', 'doctor'], name='core_fichac_fecha_c_5cff72_idx')],
            },
        ),
    ]
