# Generated by Django 5.1.3 on 2024-11-22 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_fichaclinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaclinica',
            name='diagnostico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_clinicas', to='core.diagnostico', verbose_name='Diagnóstico'),
        ),
    ]
