# Generated by Django 4.2.16 on 2024-11-09 00:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0003_remove_citamedica_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoAtencionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_servicio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo del Servicio')),
            ],
            options={
                'verbose_name': 'Costo detalle Atención',
                'verbose_name_plural': 'Costos detalles Atención',
            },
        ),
        migrations.AlterModelOptions(
            name='costosatencion',
            options={'ordering': ['-fecha_pago'], 'verbose_name': 'Costo de Atención', 'verbose_name_plural': 'Costos de Atención'},
        ),
        migrations.RenameField(
            model_name='atencion',
            old_name='comentario',
            new_name='comentario_adicional',
        ),
        migrations.RemoveField(
            model_name='costosatencion',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='costosatencion',
            name='servicios_adicionales',
        ),
        migrations.AddField(
            model_name='atencion',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='examen_fisico',
            field=models.TextField(blank=True, null=True, verbose_name='Examen Físico'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='examenes_enviados',
            field=models.TextField(blank=True, null=True, verbose_name='Examenes enviados'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='frecuencia_respiratoria',
            field=models.IntegerField(blank=True, null=True, verbose_name='Frecuencia Respiratoria(rpm)'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='presion_arterial',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Presión Arterial'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='pulso',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pulso (ppm)'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='saturacion_oxigeno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Saturación de Oxígeno (%)'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='sintomas',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Sintomas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atencion',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)'),
        ),
        migrations.AddField(
            model_name='costosatencion',
            name='fecha_pago',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha Pago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atencion',
            name='tratamiento',
            field=models.TextField(verbose_name='Plan de Tratamiento'),
        ),
        migrations.DeleteModel(
            name='ExamenSolicitado',
        ),
        migrations.AddField(
            model_name='costoatenciondetalle',
            name='costo_atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos_atenciones', to='attention.costosatencion', verbose_name='Costo Atención'),
        ),
        migrations.AddField(
            model_name='costoatenciondetalle',
            name='servicios_adicionales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_adicionales', to='attention.serviciosadicionales', verbose_name='Servicios Adicionales'),
        ),
    ]
