# Generated by Django 5.1.3 on 2024-11-19 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0004_costoatenciondetalle_alter_costosatencion_options_and_more'),
        ('core', '0009_alter_marcamedicamento_options_alter_doctor_latitud_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarioatencion',
            options={'verbose_name': 'Horario de Atención Doctor', 'verbose_name_plural': 'Horarios de Atención de los Doctores'},
        ),
        migrations.CreateModel(
            name='ExamenSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_examen', models.CharField(max_length=255, verbose_name='Nombre del Examen')),
                ('fecha_solicitud', models.DateField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo del Examen')),
                ('resultado', models.FileField(blank=True, null=True, upload_to='resultados_examenes/', verbose_name='Resultado del Examen')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('estado', models.CharField(choices=[('S', 'Solicitado'), ('R', 'Realizado')], max_length=20, verbose_name='Estado del Examen')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_examenes', to='core.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Examen Médico',
                'verbose_name_plural': 'Exámenes Médicos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
