# Generated by Django 5.1.3 on 2024-11-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0006_certificado'),
        ('core', '0009_alter_marcamedicamento_options_alter_doctor_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='diagnostico',
            field=models.ManyToManyField(related_name='certificados_diagnosticos', to='core.diagnostico', verbose_name='Diagnósticos'),
        ),
    ]
